"""
LegalLens — Local Development Server
Starts a lightweight local HTTP server with automatic browser launch and dynamic .env loading.
Usage: python run.py [port]
"""

import sys
import os
import json
import webbrowser
import http.server
import socketserver

DEFAULT_PORT = 8080

class LegalLensHandler(http.server.SimpleHTTPRequestHandler):
    """Custom HTTP request handler with dynamic .env configuration, MIME types, and CORS."""
    
    def end_headers(self):
        self.send_header('Cache-Control', 'no-cache, no-store, must-revalidate')
        self.send_header('Pragma', 'no-cache')
        self.send_header('Expires', '0')
        self.send_header('Access-Control-Allow-Origin', '*')
        super().end_headers()

    def do_GET(self):
        clean_path = self.path.split('?')[0].lstrip('/')
        if clean_path in ('config.js', ''):
            if clean_path == 'config.js':
                # Dynamically load from .env file
                env_vars = {}
                if os.path.exists('.env'):
                    try:
                        with open('.env', 'r', encoding='utf-8') as f:
                            for line in f:
                                line = line.strip()
                                if line and not line.startswith('#') and '=' in line:
                                    k, v = line.split('=', 1)
                                    env_vars[k.strip()] = v.strip()
                    except Exception as e:
                        print(f"[LegalLens] Error reading .env: {e}")

                gemini_key = env_vars.get('GEMINI_API_KEY', '')
                
                # Check for Firebase config in .env
                firebase_config = None
                if env_vars.get('FIREBASE_CONFIG'):
                    try:
                        firebase_config = json.loads(env_vars['FIREBASE_CONFIG'])
                    except Exception:
                        pass
                elif env_vars.get('FIREBASE_API_KEY'):
                    firebase_config = {
                        "apiKey": env_vars.get("FIREBASE_API_KEY", ""),
                        "authDomain": env_vars.get("FIREBASE_AUTH_DOMAIN", ""),
                        "projectId": env_vars.get("FIREBASE_PROJECT_ID", ""),
                        "storageBucket": env_vars.get("FIREBASE_STORAGE_BUCKET", ""),
                        "messagingSenderId": env_vars.get("FIREBASE_MESSAGING_SENDER_ID", ""),
                        "appId": env_vars.get("FIREBASE_APP_ID", "")
                    }

                js_content = (
                    "// Dynamically generated by run.py from local .env file\n"
                    f"window.LEGAL_LENS_CONFIG = {{\n"
                    f"  GEMINI_API_KEY: {json.dumps(gemini_key)},\n"
                    f"  FIREBASE_CONFIG: {json.dumps(firebase_config)}\n"
                    f"}};\n"
                )
                data = js_content.encode('utf-8')
                self.send_response(200)
                self.send_header('Content-Type', 'application/javascript; charset=utf-8')
                self.send_header('Content-Length', str(len(data)))
                self.end_headers()
                self.wfile.write(data)
                return

        super().do_GET()

    def log_message(self, format, *args):
        try:
            sys.stdout.write(f"[LegalLens] {args[0]} - {args[1]}\n")
            sys.stdout.flush()
        except Exception:
            pass

def run(port=DEFAULT_PORT):
    script_dir = os.path.dirname(os.path.abspath(__file__))
    os.chdir(script_dir)

    handler = LegalLensHandler
    
    try:
        with socketserver.TCPServer(("", port), handler) as httpd:
            url = f"http://localhost:{port}"
            print("=" * 60)
            print("  LegalLens - AI Legal Document Assistant")
            print("=" * 60)
            print(f"  Server running at: {url}")
            print("  .env pre-loading enabled (no frontend input needed)")
            print("  Opening browser automatically...")
            print("  Press Ctrl+C to stop the server.")
            print("=" * 60)
            sys.stdout.flush()
            
            try:
                webbrowser.open(url)
            except Exception:
                pass
                
            httpd.serve_forever()
    except OSError as e:
        if "Address already in use" in str(e) or getattr(e, 'errno', 0) in (98, 10048):
            print(f"Port {port} is in use, trying {port + 1}...")
            run(port + 1)
        else:
            raise e
    except KeyboardInterrupt:
        print("\n[LegalLens] Server stopped. Goodbye!")

if __name__ == "__main__":
    port = int(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_PORT
    run(port)
